[package]
name = "rust-aoc-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
linkme = "0.3.18"
proc-macros = { path = "./proc-macros" }
yansi = "0.5.1"
